- hosts: all
  tasks:
    - name: List the packages in windows
      win_shell: findstr "notepad++" | find /c ":"
      register: notepad_package
    - debug:
        msg: "this is {{ package_list }}"
