- hosts: all
  tasks:
   # - name: Get package content
   - name: Run multi-lined shell comman
     win_shell: |
       $available = $false
       $InstalledSoftware = Get-ChildItem "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall"
       #foreach($obj in $InstalledSoftware){
       #$obj.GetValue('DisplayName')
       # }
       foreach($obj in $InstalledSoftware){
       if($obj.GetValue('DisplayName') -match "Microsoft"){
       $available = $obj.GetValue('DisplayName')
       $available_version = $obj.GetValue('DisplayVersion')
       
       }
       }
       $available $available_version
        
     register: result
   - debug:
        var: result
      
         
    #- name: Print the package facts
      #win_command: powershell.exe Get-WmiObject -Class Win32_Product
      #win_command: powershell.exe Get-WmiObject -Class Win32_Product | where Name -eq Notepad | select Name, Version
      #win_command: pwershell.exe C:\Temp\foo.conf
      #register: notepad_package
    #- debug:
    #    msg: "this is {{ notepad_package }}"
        
    
