- hosts: all
  tasks:
    - name: copy file between locations on the remote host
      win_copy:
        src: /tmp/testcopy.txt
        remote_src: true
        dest: C:\Temp\
      register: copyresult
    - debug:
        var: copyresult
   
      
         
    #- name: Print the package facts
      #win_command: powershell.exe Get-WmiObject -Class Win32_Product
      #win_command: powershell.exe Get-WmiObject -Class Win32_Product | where Name -eq Notepad | select Name, Version
      #win_command: pwershell.exe C:\Temp\foo.conf
      #register: notepad_package
    #- debug:
    #    msg: "this is {{ notepad_package }}"
        
    
