- hosts: all
  tasks:
    - name: Find files in multiple paths
      win_find:
        paths:
          - C:\Temp
          - D:\Temp
      register: notepad_package
    - debug:
        msg: "this is {{ notepad_package }}"
        
    
