- hosts: all
  tasks:'
    #- name: Print the package facts
     #win_command: powershell.exe Get-WmiObject -Class Win32_Product | where Name -eq Notepad | select Name, Version
     # args:
     #  stdin: 
      #become: yes
    - name: Touch a file (creates if not present, updates modification time if present)
      win_file:
        path: C:\Temp\foo.conf
        state: touch
      #win_command: pwershell.exe  $available = $false  $InstalledSoftware = Get-ChildItem "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall" foreach($obj in $InstalledSoftware){ if($obj.GetValue('DisplayName') -like "Notepad++*"){
      #$available = $obj}} $available
      register: notepad_package
    - debug:
        msg: "this is {{ notepad_package }}"
        
    
