- hosts: all
  tasks:
    #- name: copy file between locations on the remote host
    #  win_copy:
    #    path: C:\Temp\test.txt
    #    state: touch
    - win_lineinfile:
        path: C:\Temp\test.txt
        line: add new Line to file
        state: present
        #newline: windows
      register: copyresult
    - debug:
        var: copyresult
   
      
         
    #- name: Print the package facts
      #win_command: powershell.exe Get-WmiObject -Class Win32_Product
      #win_command: powershell.exe Get-WmiObject -Class Win32_Product | where Name -eq Notepad | select Name, Version
      #win_command: pwershell.exe C:\Temp\foo.conf
      #register: notepad_package
    #- debug:
    #    msg: "this is {{ notepad_package }}"
        
    
