- hosts: all
  tasks:
   # - name: Get package content
   - name: Run multi-lined shell commands
     win_shell: |
       $available = $false
       $InstalledSoftware = Get-ChildItem "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall"
       $InstalledSoftware =  get-package -name notepad* |Select Name
       foreach($obj in $InstalledSoftware){
       if($obj.GetValue('DisplayName') -match "Notepad++"){
       $available = $obj.GetValue('DisplayName')
       }
       }
       $available
     register: result
   - debug:
        var: result
      
         
    #- name: Print the package facts
      #win_command: powershell.exe Get-WmiObject -Class Win32_Product
      #win_command: powershell.exe Get-WmiObject -Class Win32_Product | where Name -eq Notepad | select Name, Version
      #win_command: pwershell.exe C:\Temp\foo.conf
      #register: notepad_package
    #- debug:
    #    msg: "this is {{ notepad_package }}"
        
    
