- hosts: all
  tasks:
    - name: Print the package facts
      #win_command: powershell.exe Get-WmiObject -Class Win32_Product
      #win_command: Get-WmiObject -Class Win32_Product | where vendo -eq CodeTwo | select Name, Version
      win_command: powershell.exe Get-WmiObject -Class Win64_Product | where Name -eq Notepad++ | select Name, Version
     # args:
     #  stdin: 
      #become: yes
      register: notepad_package
    - debug:
        msg: "this is {{ notepad_package }}"
        
    
