- hosts: all
  tasks:
    - name: Print the package facts
      win_command: get-package
       #var: ansible_facts.packages
      register: notepad_package
    - debug:
        msg: "this is {{ notepad_package }}"
        
    
