- hosts: all
  tasks:
    - name: List the packages in windows
      win_find: 
         paths: C:\Temp
         patterns: notepad
      register: notepad_package
    - debug:
        msg: "this is {{ notepad_package }}"
        
    
