- hosts: all
  tasks:'
    - name: Print the package facts
     # win_command: powershell.exe Get-WmiObject -Class Win32_Product
      #win_command: powershell.exe Get-WmiObject -Class Win32_Product | where Name -eq Citrix Workspace(DV) | select Name, Version
     # win_command: powershell.exe Get-WmiObject -Class Win32_Product | where Name -eq Notepad | select Name, Version
     #win_command: powershell.exe Get-WmiObject -Class Win32_Product | where Name -eq Notepad | select Name, Version
     # args:
     #  stdin: 
      #become: yes
      win_command: pwershell.exe  $available = $false  $InstalledSoftware = Get-ChildItem "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall" foreach($obj in $InstalledSoftware){ if($obj.GetValue('DisplayName') -like "Notepad++*"){
      $available = $obj}} $available
      register: notepad_package
    - debug:
        msg: "this is {{ notepad_package }}"
        
    
