- hosts: all
  tasks:
    - name: Print the package facts
      win_command: powershell.exe get-package -Name notepad++ -AllVersions
     # args:
     #  stdin: 
      #become: yes
      register: notepad_package
    - debug:
        msg: "this is {{ notepad_package }}"
        
    
